# Generated by Django 5.0.4 on 2024-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(max_length=255)),
                ('cont_phone', models.CharField(max_length=10)),
                ('Cont_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
